Opl 74
greenfox-academy/epam-jsa-opal pull request #74
Opened 2017-10-30 06:50 UTC by ZoeCN

profile page

2017-10-30 08:17 UTC, ikarasz requested changes

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/SubscribersComponent/index.js
> +    super(props);
in this case you don't need to define the constructor function. this is the default behavior.

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/SubscribersComponent/index.js
> +        <span>{value.username}</span>
The username shouldn't be part of the url?

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/SubscribersComponent/index.js
> +      <ul>
You dont really need a list here. You can use simple `<Link>` components or `<a>` tags within a div

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/index.js
> +      this.defalutName = profileInfos.fullName;
the application will crash if you don't handle the errors

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/index.js
> +    this.setState({'profileInfos': profileInfos});
in this case you can say: 
```js
this.setState({
  profileInfos: {fullName: ev.target.value}
});
```

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/index.js
> +    this.setState({'profileInfos': profileInfos});
btw don't use apostrophe in object property names

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/index.js
> +    this.setState({'profileInfos': profileInfos});
same as above

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/index.js
> +    let obj = {
please pay attention to the variable names. Use much more talkative names

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/index.js
> +    fetch('/api/profile/' + ev.target.elements.namedItem('username').value, {
you have already collected this value, you can say obj.username... It is hard to read and also harder to the javascript engine

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/index.js
> +        console.log('field')
do not log developer stuffs to the console. It is okay for testing, but cannot go to live

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/index.js
> +        console.log('field')
i think eslint should tell this too.

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/index.js
> +            <label>Username:</label>
since the inputs are disabled we dont need to connect the label to the inputs, but in real application never forgot to connect to the given inputs.

2017-10-30 08:17 UTC, ikarasz commented on src/client/screen/ProfileScreen/index.js
> +            <input type="avatar" name="avatar" id="avatar" value={this.state.profileInfos.avatar} onChange={this.onChangeAvatar} required placeholder="avatar"/>
avatar is not a valid input type. use file type with the proper accept attribute. You can check the mdn
[input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input)
[type="file"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file)

2017-10-30 08:17 UTC, ikarasz commented on src/server/endpoints/profile-endpoint.js
> +      res.status(404).json({'error': 'not found'});
it is 401 unauthorized

2017-10-30 08:17 UTC, ikarasz commented on src/server/endpoints/profile-endpoint.js
> +        res.status(400).json({'error': 'update failed'});
it is 500 server error

2017-10-30 08:17 UTC, ikarasz commented on src/server/endpoints/profile-endpoint.js
> +      res.set('location', '/api/profile/' + updateResult.username);
we dont really use location in case of update. Only when we create a new resource. Here is no creation just modification

2017-10-30 08:17 UTC, ikarasz commented on src/server/endpoints/profile-endpoint.js
> +      res.status(404).json({'error': 'not found'});
it is 401 unauthorized

2017-10-30 08:17 UTC, ikarasz commented on src/server/endpoints/profile-endpoint.js
> +      if (userInfos._id === undefined) {
if the connection failed you return undefined, so this 'if' will crash the application ("cannot read property _id of undefined")

2017-10-30 09:43 UTC, ZoeCN commented on src/client/screen/ProfileScreen/index.js
> +    this.setState({'profileInfos': profileInfos});
it will throw errors

2017-10-30 11:11 UTC, ZoeCN commented on src/client/screen/ProfileScreen/index.js
> +            <input type="avatar" name="avatar" id="avatar" value={this.state.profileInfos.avatar} onChange={this.onChangeAvatar} required placeholder="avatar"/>
i skip this now

2017-10-31 02:10 UTC, ikarasz approved these changes

2017-10-31 02:10 UTC, ikarasz commented on src/client/screen/ProfileScreen/SubscribersComponent/index.js
> +        <span>{value.username}</span>
the name should be in the link

2017-10-31 02:46 UTC, ikarasz approved these changes

2017-10-31 03:01 UTC, merged