eslint improved
greenfox-academy/epam-jsa-opal pull request #9
Opened 2017-09-27 03:07 UTC by haochenli

make improvements to eslint improved

2017-09-27 03:24 UTC, ikarasz requested changes
please remove the .eslintrc.js from the eslintignore list

2017-09-27 03:24 UTC, ikarasz commented on .eslintrc.js
> +    'linebreak-style': 0,
we should not turn of the rule

2017-09-27 03:45 UTC, haochenli commented on .eslintrc.js
> +    'linebreak-style': 0,
OK

2017-09-28 03:10 UTC, ikarasz approved these changes

2017-09-28 03:10 UTC, merged